default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: property_listing_dev
  username: sumon
  password: 0live

test:
  <<: *default
  database: property_listing_test
  username: sumon
  password: 0live

production:
  <<: *default
  database: property_listing_prod
  username: sumon
  password: 0live
